"""Public KUMA Python SDK API.

Importing this module only binds types and functions; it does not read
credentials, inspect the environment, access the network, or create files.
"""

from ._version import __version__
from .api import configure, create_run
from .client import DEFAULT_BASE_URL, KumaClient
from .contracts import (
    CaptureComponent,
    CaptureStatus,
    Case,
    FileChange,
    FileEvidence,
    HistoryItem,
    JudgeBatchResult,
    KumaInput,
    Submission,
    TestReport,
)
from .errors import (
    AuthenticationError,
    CaseIntegrityError,
    ConfigurationError,
    DockerRequiredError,
    EvidenceCaptureError,
    InputProtocolError,
    LimitExceededError,
    PermissionDeniedError,
    ProviderError,
    RepoStateMismatchError,
    RunAlreadyActiveError,
    SensitiveDataError,
    ServiceBusyError,
    ServiceError,
    ValidationError,
)
from .exceptions import (
    KumaAPIError,
    KumaAuthenticationError,
    KumaError,
    KumaPermissionError,
    KumaRateLimitError,
    KumaTimeoutError,
)
from .repository.strategy_groups import (
    STRATEGY_GROUP_CATALOG_SCHEMA_VERSION,
    STRATEGY_GROUP_SELECTION_SCHEMA_VERSION,
    ResolvedStrategyGroup,
    StrategyGroup,
    StrategyGroupCatalog,
    StrategyGroupDeclaration,
    validate_strategy_group_catalog,
    validate_strategy_group_declaration,
    validate_strategy_group_wire_selection,
)
from .repository.tool_capabilities import (
    AGENT_CAPABILITIES_SCHEMA_VERSION,
    AgentCapabilities,
    ResourceScope,
    ToolCapability,
    scan_agent_tools,
    validate_agent_capabilities,
)
from .repository.tool_capability_io import (
    load_agent_capabilities,
    save_agent_capabilities,
    scan_agent_tool_manifest,
)

__all__ = [
    "AGENT_CAPABILITIES_SCHEMA_VERSION",
    "DEFAULT_BASE_URL",
    "STRATEGY_GROUP_CATALOG_SCHEMA_VERSION",
    "STRATEGY_GROUP_SELECTION_SCHEMA_VERSION",
    "AgentCapabilities",
    "AuthenticationError",
    "CaptureComponent",
    "CaptureStatus",
    "Case",
    "CaseIntegrityError",
    "ConfigurationError",
    "DockerRequiredError",
    "EvidenceCaptureError",
    "FileChange",
    "FileEvidence",
    "HistoryItem",
    "InputProtocolError",
    "JudgeBatchResult",
    "KumaAPIError",
    "KumaAuthenticationError",
    "KumaClient",
    "KumaError",
    "KumaInput",
    "KumaPermissionError",
    "KumaRateLimitError",
    "KumaTimeoutError",
    "LimitExceededError",
    "PermissionDeniedError",
    "ProviderError",
    "RepoStateMismatchError",
    "ResolvedStrategyGroup",
    "ResourceScope",
    "RunAlreadyActiveError",
    "SensitiveDataError",
    "ServiceBusyError",
    "ServiceError",
    "StrategyGroup",
    "StrategyGroupCatalog",
    "StrategyGroupDeclaration",
    "Submission",
    "TestReport",
    "ToolCapability",
    "ValidationError",
    "__version__",
    "configure",
    "create_run",
    "load_agent_capabilities",
    "save_agent_capabilities",
    "scan_agent_tool_manifest",
    "scan_agent_tools",
    "validate_agent_capabilities",
    "validate_strategy_group_catalog",
    "validate_strategy_group_declaration",
    "validate_strategy_group_wire_selection",
]
